development:
  adapter: postgresql
  database: reibotdev
  username: reibot-test
  password: shenanigans87
  host: alternia.tkware.info
  pool: 5
  timeout: 5000
  schema_search_path: public

production:
  adapter: postgresql
